version: "3.9"


services:
  web:
    build: .
    restart: always
    command: python manage.py
    volumes:
      - .:/usr/src/app/
    ports:
      - 8080:8080
    links:
      - db

  db:
    image: postgres:13
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=avitotask
volumes:
  data:
    external:
      True

